//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by BitmapCutter.rc
//
#define IDD_BITMAPCUTTER_DIALOG         102
#define IDR_MAINFRAME                   128
#define IDC_PIC                         1000
#define IDC_PIC_INS                     1000
#define IDC_BUTTON_FILE                 1001
#define IDC_BUTTON_FILE_INS             1001
#define IDC_FILE                        1002
#define IDC_FILE_INS                    1002
#define IDC_BMPSIZE                     1003
#define IDC_BMPSIZE_INS                 1003
#define IDC_X1                          1004
#define IDC_BUTTON_FILE_OUTS            1004
#define IDC_X2                          1005
#define IDC_FILE_OUTS                   1005
#define IDC_X3                          1006
#define IDC_BUTTON_FILE_HOVERS          1006
#define IDC_X4                          1007
#define IDC_FILE_HOVERS                 1007
#define IDC_Y1                          1008
#define IDC_PIC_OUTS                    1008
#define IDC_Y2                          1009
#define IDC_PIC_HOVERS                  1009
#define IDC_Y3                          1010
#define IDC_INS_LABEL                   1010
#define IDC_Y4                          1011
#define IDC_OUTS_LABEL                  1011
#define IDC_Y5                          1012
#define IDC_HOVERS_LABEL                1012
#define IDC_Y6                          1013
#define IDC_BMPSIZE_OUTS                1013
#define IDC_GO                          1014
#define IDC_BMPSIZE_HOVERS              1014
#define IDC_SAVE                        1015
#define IDC_DESTDIR                     1016
#define IDC_BUTTON_DEST                 1017
#define IDC_CANCEL                      1018
#define IDC_INS                         1019
#define IDC_OUTS                        1020
#define IDC_DRAWSAVE                    1021
#define IDC_VP                          1022
#define IDC_ZERO                        1022
#define IDC_VB                          1023
#define IDC_PIC_TEST                    1023
#define IDC_DRAW                        1024
#define IDC_REREAD                      1025
#define IDC_HOVER                       1026
#define IDC_REMOVE_DRAW                 1027
#define IDC_RED                         1028
#define IDC_GREEN                       1029
#define IDC_BLUE                        1030
#define IDC_BLACK_WHITE                 1031
#define IDC_OTHER                       1032
#define IDC_LINEWIDTH                   1033
#define IDC_STOP_X                      1034
#define IDC_STOP_Y                      1035
#define IDC_STOP_WIDTH                  1036
#define IDC_STOP_HEIGHT                 1037
#define IDC_PLAY_X                      1038
#define IDC_PLAY_Y                      1039
#define IDC_PLAY_WIDTH                  1040
#define IDC_PLAY_HEIGHT                 1041
#define IDC_PAUSE_X                     1042
#define IDC_PAUSE_Y                     1043
#define IDC_PAUSE_WIDTH                 1044
#define IDC_PAUSE_HEIGHT                1045
#define IDC_REVERSE_X                   1046
#define IDC_REVERSE_Y                   1047
#define IDC_REVERSE_WIDTH               1048
#define IDC_REVERSE_HEIGHT              1049
#define IDC_FORWARD_X                   1050
#define IDC_FORWARD_Y                   1051
#define IDC_FORWARD_WIDTH               1052
#define IDC_FORWARD_HEIGHT              1053
#define IDC_RANDOM_X                    1054
#define IDC_RANDOM_Y                    1055
#define IDC_RANDOM_WIDTH                1056
#define IDC_RANDOM_HEIGHT               1057
#define IDC_SHUFFLE_X                   1058
#define IDC_SHUFFLE_Y                   1059
#define IDC_SHUFFLE_WIDTH               1060
#define IDC_SHUFFLE_HEIGHT              1061
#define IDC_CLEAR_X                     1062
#define IDC_CLEAR_Y                     1063
#define IDC_CLEAR_WIDTH                 1064
#define IDC_CLEAR_HEIGHT                1065
#define IDC_LOAD_X                      1066
#define IDC_LOAD_Y                      1067
#define IDC_LOAD_WIDTH                  1068
#define IDC_LOAD_HEIGHT                 1069
#define IDC_SAVE_X                      1070
#define IDC_SAVE_Y                      1071
#define IDC_SAVE_WIDTH                  1072
#define IDC_SAVE_HEIGHT                 1073
#define IDC_VOLUME_X                    1074
#define IDC_VOLUME_Y                    1075
#define IDC_VOLUME_WIDTH                1076
#define IDC_VOLUME_HEIGHT               1077
#define IDC_PROGRESS_X                  1078
#define IDC_PROGRESS_Y                  1079
#define IDC_PROGRESS_WIDTH              1080
#define IDC_PROGRESS_HEIGHT             1081
#define IDC_STATIC_STOP                 1082
#define IDC_STATIC_PLAY                 1083
#define IDC_STATIC_PAUSE                1084
#define IDC_STATIC_REVERSE              1085
#define IDC_STATIC_FORWARD              1086
#define IDC_STATIC_RANDOM               1087
#define IDC_STATIC_SHUFFLE              1088
#define IDC_STATIC_CLEAR                1089
#define IDC_STATIC_LOAD                 1090
#define IDC_STATIC_SAVE                 1091
#define IDC_STATIC_VOLUME               1092
#define IDC_STATIC_PROGRESS             1093
#define IDC_TEST_LABEL                  1094
#define IDC_BUTTON1                     1095
#define IDC_BUTTON2                     1096
#define IDC_BUTTON3                     1097
#define IDC_BUTTON4                     1098
#define IDC_BUTTON5                     1099
#define IDC_BUTTON6                     1100
#define IDC_BUTTON7                     1101
#define IDC_BUTTON8                     1102
#define IDC_BUTTON9                     1103
#define IDC_BUTTON10                    1104
#define IDC_TVOLUME                     1105
#define IDC_TPROGRESS                   1106
#define IDC_START_WIDTH                 1107
#define IDC_CLR_BTN_FG_HOV              1107
#define IDC_CLR_BTN_BG_HOV              1108
#define IDC_MENU_X                      1109
#define IDC_RED2                        1110
#define IDC_SAVESKINDEF                 1110
#define IDC_GREEN2                      1111
#define IDC_BLUE2                       1112
#define IDC_MENU_Y                      1113
#define IDC_RED3                        1114
#define IDC_GREEN3                      1115
#define IDC_BLUE3                       1116
#define IDC_MENU_WIDTH                  1117
#define IDC_MENU_HEIGHT                 1118
#define IDC_STATIC_MENU                 1119
#define IDC_MUSIC_X                     1120
#define IDC_MUSIC_Y                     1121
#define IDC_MUSIC_WIDTH                 1122
#define IDC_MUSIC_HEIGHT                1123
#define IDC_STATIC_MUSIC                1124
#define IDC_PICTURES_X                  1125
#define IDC_PICTURES_Y                  1126
#define IDC_PICTURES_WIDTH              1127
#define IDC_PICTURES_HEIGHT             1128
#define IDC_STATIC_PICTURES             1129
#define IDC_VIDEO_X                     1130
#define IDC_VIDEO_Y                     1131
#define IDC_VIDEO_WIDTH                 1132
#define IDC_VIDEO_HEIGHT                1133
#define IDC_STATIC_VIDEO                1134
#define IDC_BUTTON11                    1135
#define IDC_BUTTON12                    1136
#define IDC_BUTTON13                    1137
#define IDC_BUTTON14                    1138
#define IDC_BGTYPE_STRETCHED            1139
#define IDC_BGTYPE_TILED                1140
#define IDC_BGTYPE_FIXED                1141
#define IDC_BUTTON_FILE_SETTINGS        1142
#define IDC_FILE_SETTINGS               1143
#define IDC_CLR_BTN_FG_OUT              1144
#define IDC_CLR_BTN_BG_OUT              1145
#define IDC_CLR_OTHER_BG                1147
#define IDC_CLR_OTHER_FG                1148
#define IDC_CLR_TRANSMAIN               1149
#define IDC_CLR_TRANSPANEL              1150

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        129
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1144
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
