//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by muzikbrowzer.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_PLAYER_DIALOG               102
#define IDP_SOCKETS_INIT_FAILED         103
#define IDD_PROPPAGE_LARGE              107
#define IDD_ENTER_URL_DIALOG            129
#define IDI_XAUDIO_ICON                 129
#define IDC_CURSOR1                     130
#define IDI_WEB_ICON                    131
#define IDD_INFO_DIALOG                 132
#define IDD_VOLUME_DIALOG               133
#define IDD_EQUALIZER_DIALOG            134
#define IDD_INIT_DIALOG                 136
#define IDR_MENU1                       142
#define IDD_CONFIG_DIALOG               143
#define IDD_CONFIG_IR                   143
#define IDR_MENU2                       147
#define IDD_MENU_DIALOG                 148
#define IDD_CONFIG_SETTINGS             155
#define IDC_CURSOR2                     156
#define IDD_SAVEPLAYLISTDIALOG          158
#define IDD_LOADPLAYLISTDLG             159
#define IDD_SCAN_RESULTS                160
#define IDD_ID3TAG_DIALOG               161
#define IDD_ID3_DISPLAY                 162
#define IDD_ID3MODIFY_STATUS            164
#define IDC_CURSOR3                     165
#define IDD_MESSAGE_DIALOG              167
#define IDD_DIALOG1                     168
#define IDD_CONFIG_FONTS                169
#define IDD_CONFIG_COLORS               170
#define IDD_CONFIG_FILES                171
#define IDD_CONFIG_IRMAN                172
#define IDB_GLYPHS                      174
#define IDB_SCROLLDOWNARROW             176
#define IDB_SCROLLUPARROW               177
#define IDB_SCROLLBUTTON                178
#define IDB_SCREENSHOT                  181
#define IDB_BITMAP1                     189
#define IDB_RED_BUTTON                  189
#define IDB_BITMAP2                     190
#define IDB_BITMAP3                     191
#define IDI_MBLOGO                      192
#define IDI_MBLOGO1616                  193
#define IDI_MBLOGO3232                  194
#define IDB_BITMAP4                     195
#define IDB_BITMAP5                     197
#define IDB_BUTTON_RESTORE              198
#define IDB_BUTTON_MAXIMIZE             199
#define IDB_BUTTON_MINIMIZE             200
#define IDB_BUTTON_EXIT                 201
#define IDD_CONFIG_PASSWORD             203
#define IDI_MBLOGO3                     209
#define IDD_PICTUREDLG                  210
#define IDD_SPLASH_DIALOG               211
#define IDB_BITMAP6                     212
#define IDB_SPLASH2                     214
#define IDB_SPLASH3                     215
#define IDR_APPGIF                      227
#define IDB_BITMAP7                     228
#define IDB_BITMAP8                     230
#define IDD_CONFIG_DISPLAY              232
#define IDB_BITMAP9                     233
#define IDB_GROUP_TEST                  248
#define IDB_BITMAP10                    250
#define IDB_BITMAP11                    251
#define IDD_FRACTAL_DLG                 252
#define IDC_VOLUME_BUTTON               1000
#define IDC_STOP_BUTTON                 1001
#define IDC_PLAY_BUTTON                 1002
#define IDC_ABOUT_BUTTON                1003
#define IDC_INFO_BUTTON                 1004
#define IDC_SLIDER                      1005
#define IDC_POSITION_SLIDER             1005
#define IDC_EQUALIZER_BUTTON            1006
#define IDC_VOLUME_SLIDER               1006
#define IDC_DURATION_LABEL              1007
#define IDC_URL_EDIT                    1007
#define IDC_TIMECODE_LABEL              1008
#define IDC_NAME_LABEL                  1009
#define IDC_OPEN_FILE_BUTTON            1010
#define IDC_OPEN_URL_BUTTON             1011
#define IDC_TYPE_LABEL                  1012
#define IDC_STATE_LABEL                 1013
#define IDC_PLAYING_LABEL               1013
#define IDC_AUTOPLAY_CHECKBOX           1014
#define IDC_XAUDIO_STATUS               1014
#define IDC_PLAYER_STATUS               1014
#define IDC_INPUT_LIST                  1015
#define IDC_POSITION_LABEL              1015
#define IDC_OUTPUT_LIST                 1016
#define IDC_VOLUME_LABEL                1016
#define IDC_LIBRARY_VERSION_LABEL       1017
#define IDC_ASYNC_VERSION_LABEL         1017
#define IDC_CURRENT_TITLE               1017
#define IDC_MASTER_SLIDER               1018
#define IDC_CODEC_LIST                  1018
#define IDC_PCM_SLIDER                  1019
#define IDC_SYNC_VERSION_LABEL          1019
#define IDC_BALANCE_SLIDER              1020
#define IDC_IMPL_VERSION_LABEL          1020
#define IDC_ENABLE_EQ_CHECKBOX          1021
#define IDC_SLIDER1                     1022
#define IDC_SLIDER2                     1023
#define IDC_SLIDER3                     1024
#define IDC_NETWORK_PROGRESS1           1024
#define IDC_SLIDER4                     1025
#define IDC_NETWORK_STATUS_LABEL        1025
#define IDC_SLIDER5                     1026
#define IDC_NETWORK_PROGRESS2           1026
#define IDC_SLIDER6                     1027
#define IDC_STREAM_PROPERTIES           1027
#define IDC_SLIDER7                     1028
#define IDC_SLIDER8                     1029
#define IDC_LIST1                       1033
#define IDC_ARTISTS                     1033
#define IDC_DIRLIST                     1033
#define IDC_PLAYLIST_NAMES              1033
#define IDC_LIST2                       1037
#define IDC_ALBUMS                      1037
#define IDC_PLAYLIST_SONGS              1037
#define IDC_MP3_EXTENSION               1037
#define IDC_LIST3                       1038
#define IDC_SONGS                       1038
#define IDC_LIST4                       1039
#define IDC_PLAYLIST                    1039
#define IDC_GENRES                      1041
#define IDC_MENU_BUTTON                 1042
#define IDC_INIT_STATUS                 1043
#define IDC_IRRECORD                    1066
#define IDC_IRTEST                      1067
#define IDC_IRINITIALIZE                1068
#define IDC_IRCOMPORT_STATUS            1069
#define IDC_IRNONE                      1105
#define IDC_IRCOM1                      1106
#define IDC_IRCOM2                      1107
#define IDC_IRCOM3                      1108
#define IDC_IRCOM4                      1109
#define IDC_IRCOM5                      1110
#define IDC_IRCOM6                      1111
#define IDC_IRCOM7                      1112
#define IDC_IRCOM8                      1113
#define IDC_IRDELAY                     1114
#define IDC_IRTEST_STATUS               1116
#define IDC_PMENUEXIT                   1119
#define IDC_PMENUSHUFFLEPLAYLIST        1120
#define IDC_PMENUCLEARPLAYLIST          1121
#define IDC_PMENURANDOMIZEPLAYLIST      1122
#define IDC_PMENULOADPLAYLIST           1123
#define IDC_PMENUPAUSE                  1124
#define IDC_PMENUPLAY                   1125
#define IDC_PMENUSTOP                   1126
#define IDC_PMENUHELP                   1127
#define IDC_DIRADD                      1128
#define IDC_PMENUSAVEPLAYLIST           1128
#define IDC_DIRREMOVE                   1129
#define IDC_DIRSCAN                     1130
#define IDC_DIRSCAN_NEW                 1131
#define IDC_IRCONFIG_BUTTON             1132
#define IDC_LOCATION_BUTTON             1133
#define IDC_MDB_LOCATION                1134
#define IDC_SAVEPLAYLIST_BOX            1136
#define IDC_SCAN_RESULTS                1139
#define IDC_EDIT_ARTIST                 1141
#define IDC_EDIT_ALBUM                  1142
#define IDC_EDIT_TITLE                  1143
#define IDC_EDIT_TRACK                  1144
#define IDC_EDIT_YEAR                   1145
#define IDC_OLDGENRE                    1146
#define IDC_OLDARTIST                   1147
#define IDC_OLDALBUM                    1148
#define IDC_OLDYEAR                     1149
#define IDC_OLDTITLE                    1150
#define IDC_OLDTRACK                    1151
#define IDC_MOREID3                     1152
#define IDC_ID3_DISPLAY                 1153
#define IDC_TAG_FILE                    1153
#define IDC_EDIT_GENRE                  1154
#define IDC_ID3MODIFY_PROGRESS          1160
#define IDC_ID3MODIFY_LABEL             1161
#define IDC_ID3MODIFY_STATUS            1162
#define IDC_INIT_LABEL                  1163
#define IDC_INIT_PROGRESS               1164
#define IDC_INIT_ABORT                  1165
#define IDC_MP3_REMOVE                  1167
#define IDC_MP3_ADD_EXT                 1168
#define IDC_MP3_ADD                     1169
#define IDC_GENRESLABEL                 1169
#define IDC_ARTISTSLABEL                1170
#define IDC_ALBUMSLABEL                 1171
#define IDC_SONGSLABEL                  1172
#define IDC_PLAYLISTLABEL               1173
#define IDC_MESSAGE_BOX                 1178
#define IDC_CANCEL                      1179
#define IDC_PLAYLIST_CANCEL             1179
#define IDC_FONT_BUTTON                 1180
#define IDC_PLAYLIST_DELETE             1180
#define IDC_GO                          1180
#define IDC_PLAYLIST_LOAD               1181
#define IDC_GAAS                        1183
#define IDC_BUTTON2                     1186
#define IDC_OPTIONS_BUTTON              1186
#define IDC_THEME_DELETE                1186
#define IDC_BUTTON_MINIMIZE             1187
#define IDC_SKIN_DELETE                 1187
#define IDC_BUTTON_MAXIMIZE             1188
#define IDC_BUTTON_EXIT                 1189
#define IDC_BUTTON_STOP                 1190
#define IDC_FONT                        1191
#define IDC_BUTTON_PLAY                 1191
#define IDC_FONT2                       1192
#define IDC_FONT_PANEL                  1192
#define IDC_BUTTON_PAUSE                1192
#define IDC_FONT_COLHDR                 1193
#define IDC_BUTTON_REVERSE              1193
#define IDC_FONTSIZE                    1194
#define IDC_BUTTON_RESIZE               1194
#define IDC_SAMPLE                      1195
#define IDC_SAMPLE_TITLES               1195
#define IDC_BUTTON_FASTFORWARD          1195
#define IDC_BOLD                        1196
#define IDC_BOLD_TITLES                 1196
#define IDC_BUTTON_RANDOM               1196
#define IDC_FONTSIZE2                   1197
#define IDC_FONTSIZE_PANEL              1197
#define IDC_BUTTON_SHUFFLE              1197
#define IDC_SAMPLE2                     1198
#define IDC_SAMPLE_PANEL                1198
#define IDC_BUTTON_CLEAR                1198
#define IDC_SET_DEFAULT                 1199
#define IDC_BORDER_WIDTH                1199
#define IDC_BUTTON_LOAD                 1199
#define IDC_COLOR_BK_NORMAL             1200
#define IDC_BUTTON_SAVE                 1200
#define IDC_COLOR_BK_HIGH               1201
#define IDC_COLOR_BK_SEL                1202
#define IDC_COLOR_TX_NORMAL             1203
#define IDC_COLOR_TX_HIGH               1204
#define IDC_COLOR_TX_SEL                1205
#define IDC_COLOR_BK_PANEL              1206
#define IDC_COLOR_TX_PANEL              1207
#define IDC_SCROLLBAR1                  1208
#define IDC_COLOR_BK_COLHDR             1208
#define IDC_RUNATSTARTUP                1209
#define IDC_COLOR_TX_COLHDR             1209
#define IDC_HYPERLINK                   1210
#define IDC_FONTSIZE_COLHDR             1210
#define IDC_PRODVERSION                 1211
#define IDC_SAMPLE_HIGH                 1211
#define IDC_APP_LABEL                   1212
#define IDC_SAMPLE_SEL                  1212
#define IDC_BOLD2                       1213
#define IDC_SAMPLE_COLHDR               1213
#define IDC_COLOR_BORDERS               1214
#define IDC_COLOR_BK_CTRLS              1215
#define IDC_COLOR_TX_CTRLS              1216
#define IDC_BORDER_PANEL                1217
#define IDC_BORDER_HORZ                 1218
#define IDC_BORDER_VERT                 1219
#define IDC_IRUP                        1500
#define IDC_IRDOWN                      1501
#define IDC_IRLEFT                      1502
#define IDC_IRRIGHT                     1503
#define IDC_IRSELECT                    1504
#define IDC_IRMENU                      1505
#define IDC_IREXIT                      1506
#define IDC_IRDELETE                    1507
#define IDC_IRVOLUP                     1508
#define IDC_IRVOLDOWN                   1509
#define IDC_IRPAGEUP                    1510
#define IDC_IRPAGEDOWN                  1511
#define IDC_IRPLAY                      1512
#define IDC_IRPAUSE                     1513
#define IDC_IRSTOP                      1514
#define IDC_IRNEXT                      1515
#define IDC_IRPREVIOUS                  1516
#define IDC_IRFASTFORWARD               1517
#define IDC_IRREVERSE                   1518
#define IDC_IRALPHAUP                   1519
#define IDC_IRALPHADOWN                 1520
#define IDC_IRUP_DESC                   1600
#define IDC_IRDOWN_DESC                 1601
#define IDC_IRLEFT_DESC                 1602
#define IDC_IRRIGHT_DESC                1603
#define IDC_IRSELECT_DESC               1604
#define IDC_IRMENU_DESC                 1605
#define IDC_IREXIT_DESC                 1606
#define IDC_IRDELETE_DESC               1607
#define IDC_IRVOLUP_DESC                1608
#define IDC_IRVOLDOWN_DESC              1609
#define IDC_IRPAGEUP_DESC               1610
#define IDC_IRPAGEDOWN_DESC             1611
#define IDC_IRPLAY_DESC                 1612
#define IDC_IRPAUSE_DESC                1613
#define IDC_IRSTOP_DESC                 1614
#define IDC_IRNEXT_DESC                 1615
#define IDC_IRPREVIOUS_DESC             1616
#define IDC_IRFASTFORWARD_DESC          1617
#define IDC_IRREVERSE_DESC              1618
#define IDC_IRALPHAUP_DESC              1619
#define IDC_IRALPHADOWN_DESC            1620
#define IDC_IRUP_STATUS                 1700
#define IDC_IRDOWN_STATUS               1701
#define IDC_IRLEFT_STATUS               1702
#define IDC_IRRIGHT_STATUS              1703
#define IDC_IRSELECT_STATUS             1704
#define IDC_IRMENU_STATUS               1705
#define IDC_IREXIT_STATUS               1706
#define IDC_IRDELETE_STATUS             1707
#define IDC_IRVOLUP_STATUS              1708
#define IDC_IRVOLDOWN_STATUS            1709
#define IDC_IRPAGEUP_STATUS             1710
#define IDC_IRPAGEDOWN_STATUS           1711
#define IDC_IRPLAY_STATUS               1712
#define IDC_IRPAUSE_STATUS              1713
#define IDC_IRSTOP_STATUS               1714
#define IDC_IRNEXT_STATUS               1715
#define IDC_IRPREVIOUS_STATUS           1716
#define IDC_IRFASTFORWARD_STATUS        1717
#define IDC_IRREVERSE_STATUS            1718
#define IDC_IRALPHAUP_STATUS            1719
#define IDC_IRALPHADOWN_STATUS          1720
#define IDC_MESSAGEBOX_OK               2001
#define IDC_CP_FIRSTNAME                2002
#define IDC_MESSAGEBOX_CANCEL           2002
#define IDC_CP_LASTNAME                 2003
#define IDC_CP_PASSWORD                 2004
#define IDC_CP_EMAIL                    2005
#define IDC_CP_HOSTID                   2006
#define IDC_SENDINFO                    2008
#define IDC_PASSWORD_MSG                2009
#define IDC_VALIDATE_PW                 2010
#define IDC_CP_TRIAL_EXPIRATION         2012
#define IDC_CP_TRIAL_LABEL              2013
#define IDC_PICTURE                     2014
#define IDC_PICTURE_CTRL                2016
#define IDC_USEGENRE                    2018
#define IDC_ALBUMSORT_DATE              2019
#define IDC_ALBUMSORT_ALPHA             2020
#define IDC_BOLD_PANEL                  2020
#define IDC_BOLD_COLHDR                 2021
#define IDC_THEME_CREATE                2024
#define IDC_THEME_LIST                  2026
#define IDC_ROUND_CORNERS               2027
#define IDC_SKIN_LIST                   2028
#define IDC_PLAYLIST_HEIGHT             2031
#define IDC_SPIN_PLAYLIST               2032
#define IDC_GENRE_WIDTH                 2033
#define IDC_SPIN_GENRE                  2034
#define IDC_EASTEREGG                   2036
#define IDC_BUTTON_PLAY2                2039
#define ID_XXX                          32775
#define ID__EXIT                        32785
#define ID_PMENU_EXIT                   32785
#define ID__SHUFFLE                     32786
#define ID_PMENU_SHUFFLE                32786
#define ID__CLEAR                       32787
#define ID_PMENU_CLEAR                  32787
#define ID__SAVEPLAYLIST                32788
#define ID__LOADPLAYLIST                32789
#define ID_PMENU_LOADPLAYLIST           32789
#define ID__CONFIG                      32791
#define ID_MENU_EXIT                    32793
#define ID_MENU_SHUFFLEPLAYLIST         32794
#define ID_MENU_CLEARPLAYLIST           32795
#define ID_MENU_LOADPLAYLIST            32796
#define ID_MENU_SAVEPLAYLIST            32797
#define ID_MENU                         32798
#define ID_MENU_OPTIONS                 32799
#define ID_PMENU_PAUSE                  32800
#define ID_PMENU_PLAY                   32801
#define ID_PMENU_STOP                   32802
#define ID_MENUITEM32803                32803
#define ID_PMENU_HELP                   32804
#define ID_MENU_HELP                    32805
#define ID_MENU_PAUSE                   32806
#define ID_MENU_PLAY                    32807
#define ID_MENU_STOP                    32808
#define ID_EDIT_ID3TAG                  32810
#define IDD_ABOUT                       32811
#define ID_MENU_RANDOMIZE_PLAYLIST      32813
#define ID_MYTEST                       32815
#define ID_MENU_EXPORT                  32816

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        253
#define _APS_NEXT_COMMAND_VALUE         32817
#define _APS_NEXT_CONTROL_VALUE         2039
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
