//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by muzikbrowzer.rc
//
#define IDB_BITMAP1                     16
#define IDB_BITMAP2                     17
#define IDB_BITMAP3                     18
#define IDB_BITMAP4                     19
#define IDB_BITMAP5                     20
#define IDB_BITMAP6                     21
#define IDB_BITMAP7                     22
#define IDB_BITMAP8                     23
#define IDB_BITMAP9                     24
#define IDB_BITMAP10                    25
#define IDB_BITMAP11                    26
#define IDB_BUTTON_EXIT                 27
#define IDB_BUTTON_MAXIMIZE             28
#define IDB_BUTTON_MINIMIZE             29
#define IDB_BUTTON_RESTORE              30
#define IDB_GLYPHS                      31
#define IDB_GROUP_TEST                  32
#define IDB_OBM_DNARROW                 33
#define IDB_OBM_SCRLBG                  34
#define IDB_OBM_SCRLBTN                 35
#define IDB_OBM_UPARROW                 36
#define IDB_RED_BUTTON                  37
#define IDB_SCREENSHOT                  38
#define IDB_SCROLLBUTTON                39
#define IDB_SCROLLDOWNARROW             40
#define IDB_SCROLLUPARROW               41
#define IDB_SPLASH2                     42
#define IDB_SPLASH3                     43
#define IDD_ABOUT                       44
#define IDD_ABOUTBOX                    45
#define IDD_CONFIG_COLORS               46
#define IDD_CONFIG_DIALOG               47
#define IDD_CONFIG_DISPLAY              48
#define IDD_CONFIG_FILES                49
#define IDD_CONFIG_FONTS                50
#define IDD_CONFIG_IR                   51
#define IDD_CONFIG_IRMAN                52
#define IDD_CONFIG_PASSWORD             53
#define IDD_CONFIG_SETTINGS             54
#define IDD_DIALOG1                     55
#define IDD_DIALOG2                     56
#define IDD_ENTER_URL_DIALOG            57
#define IDD_EQUALIZER_DIALOG            58
#define IDD_EXPORT_DLG                  59
#define IDD_FILEANDFOLDER               60
#define IDD_FRACTAL_DLG                 61
#define IDD_GETBLACKOUT_DIALOG          62
#define IDD_GETTEXTFIELD                63
#define IDD_ID3_DISPLAY                 64
#define IDD_ID3MODIFY_STATUS            65
#define IDD_ID3TAG_DIALOG               66
#define IDD_INFO_DIALOG                 67
#define IDD_INIT_DIALOG                 68
#define IDD_LOADPLAYLISTDLG             69
#define IDD_MENU_DIALOG                 70
#define IDD_MESSAGE_DIALOG              71
#define IDD_PICTUREDLG                  72
#define IDD_PLAYER_DIALOG               73
#define IDD_PROGRESS_DLG                74
#define IDD_PROPPAGE_LARGE              75
#define IDD_SAVEPLAYLISTDIALOG          76
#define IDD_SCAN_RESULTS                77
#define IDD_SPLASH_DIALOG               78
#define IDD_TESTCANCELDLG               79
#define IDD_VOLUME_DIALOG               80
#define IDI_ICON1                       81
#define IDI_ICON_V2                     82
#define IDI_MBLOGO                      83
#define IDI_MBLOGO3                     84
#define IDI_MBLOGO1616                  85
#define IDI_MBLOGO3232                  86
#define IDI_WEB_ICON                    87
#define IDI_XAUDIO_ICON                 88
#define IDM_ABOUTBOX                    89
#define IDP_SOCKETS_INIT_FAILED         90
#define IDR_APPGIF                      91
#define IDR_MENU1                       92
#define IDR_MENU2                       93
#define IDS_ABOUTBOX                    94
#define IDS_UNKNOWN_ERROR               95
#define IDC_3DCOLHDRS                   130
#define IDC_3DDATA                      131
#define IDC_3DSTATUS                    132
#define IDC_ABOUT_BUTTON                133
#define IDC_ABOUT_COPYRIGHT             134
#define IDC_ALBUMS                      135
#define IDC_ALBUMSLABEL                 136
#define IDC_ALBUMSORT_ALPHA             137
#define IDC_ALBUMSORT_DATE              138
#define IDC_APP_LABEL                   139
#define IDC_ARTISTS                     140
#define IDC_ARTISTSLABEL                141
#define IDC_ASYNC_VERSION_LABEL         142
#define IDC_AUTOPLAY_CHECKBOX           143
#define IDC_BALANCE_SLIDER              144
#define IDC_BOLD                        145
#define IDC_BOLD2                       146
#define IDC_BOLD_COLHDR                 147
#define IDC_BOLD_CURPLY                 148
#define IDC_BOLD_PANEL                  149
#define IDC_BOLD_TITLES                 150
#define IDC_BORDER_HORZ                 151
#define IDC_BORDER_PANEL                152
#define IDC_BORDER_VERT                 153
#define IDC_BORDER_WIDTH                154
#define IDC_BUTTON1                     155
#define IDC_BUTTON2                     156
#define IDC_BUTTON_CLEAR                157
#define IDC_BUTTON_D                    158
#define IDC_BUTTON_DL                   159
#define IDC_BUTTON_DR                   160
#define IDC_BUTTON_EXIT                 161
#define IDC_BUTTON_FASTFORWARD          162
#define IDC_BUTTON_L                    163
#define IDC_BUTTON_LOAD                 164
#define IDC_BUTTON_LOGO                 165
#define IDC_BUTTON_MAXIMIZE             166
#define IDC_BUTTON_MINIMIZE             167
#define IDC_BUTTON_PAUSE                168
#define IDC_BUTTON_PLAY                 169
#define IDC_BUTTON_R                    170
#define IDC_BUTTON_RANDOM               171
#define IDC_BUTTON_RESIZE               172
#define IDC_BUTTON_RESTORE              173
#define IDC_BUTTON_REVERSE              174
#define IDC_BUTTON_SAVE                 175
#define IDC_BUTTON_SHUFFLE              176
#define IDC_BUTTON_STOP                 177
#define IDC_BUTTON_U                    178
#define IDC_BUTTON_UL                   179
#define IDC_BUTTON_UR                   180
#define IDC_BUTTON_W                    181
#define IDC_CANCEL                      182
#define IDC_CODEC_LIST                  183
#define IDC_COLOR_BK_COLHDR             184
#define IDC_COLOR_BK_CTRLS              185
#define IDC_COLOR_BK_CURPLY             186
#define IDC_COLOR_BK_HIGH               187
#define IDC_COLOR_BK_NORMAL             188
#define IDC_COLOR_BK_PANEL              189
#define IDC_COLOR_BK_SEL                190
#define IDC_COLOR_BORDERS               191
#define IDC_COLOR_COLHDR_INLR           192
#define IDC_COLOR_COLHDR_INUL           193
#define IDC_COLOR_COLHDR_OUTLR          194
#define IDC_COLOR_COLHDR_OUTUL          195
#define IDC_COLOR_DATA_INLR             196
#define IDC_COLOR_DATA_INUL             197
#define IDC_COLOR_DATA_OUTLR            198
#define IDC_COLOR_DATA_OUTUL            199
#define IDC_COLOR_STATUS_INLR           200
#define IDC_COLOR_STATUS_INUL           201
#define IDC_COLOR_STATUS_OUTLR          202
#define IDC_COLOR_STATUS_OUTUL          203
#define IDC_COLOR_TX_COLHDR             204
#define IDC_COLOR_TX_CTRLS              205
#define IDC_COLOR_TX_CURPLY             206
#define IDC_COLOR_TX_HIGH               207
#define IDC_COLOR_TX_NORMAL             208
#define IDC_COLOR_TX_PANEL              209
#define IDC_COLOR_TX_SEL                210
#define IDC_CP_EMAIL                    211
#define IDC_CP_FIRSTNAME                212
#define IDC_CP_HOSTID                   213
#define IDC_CP_LASTNAME                 214
#define IDC_CP_PASSWORD                 215
#define IDC_CP_TRIAL_EXPIRATION         216
#define IDC_CP_TRIAL_LABEL              217
#define IDC_CURRENT_TITLE               218
#define IDC_CURSOR1                     219
#define IDC_CURSOR2                     220
#define IDC_CURSOR3                     221
#define IDC_CURSOR4                     222
#define IDC_DEBUG_LOG                   223
#define IDC_DIRADD                      224
#define IDC_DIRADD2                     225
#define IDC_DIRCLEAR                    226
#define IDC_DIRLIST                     227
#define IDC_DIRLIST2                    228
#define IDC_DIRREMOVE                   229
#define IDC_DIRREMOVE2                  230
#define IDC_DIRSCAN                     231
#define IDC_DIRSCAN_NEW                 232
#define IDC_DISPLAY_COMMENTS            233
#define IDC_DURATION_LABEL              234
#define IDC_EASTEREGG                   235
#define IDC_EDIT_ALBUM                  236
#define IDC_EDIT_ARTIST                 237
#define IDC_EDIT_GENRE                  238
#define IDC_EDIT_TITLE                  239
#define IDC_EDIT_TRACK                  240
#define IDC_EDIT_YEAR                   241
#define IDC_ENABLE_EQ_CHECKBOX          242
#define IDC_EQUALIZER_BUTTON            243
#define IDC_EXCLUDECLEAR                244
#define IDC_EXPORT_ALBUM                245
#define IDC_EXPORT_ARTIST               246
#define IDC_EXPORT_CSV                  247
#define IDC_EXPORT_DIR                  248
#define IDC_EXPORT_EXTRA_KEYS           249
#define IDC_EXPORT_FILE                 250
#define IDC_EXPORT_GENRE                251
#define IDC_EXPORT_HTML                 252
#define IDC_EXPORT_LENGTH               253
#define IDC_EXPORT_MP3FILE              254
#define IDC_EXPORT_SONG                 255
#define IDC_EXPORT_TMPL                 256
#define IDC_EXPORT_TRACK                257
#define IDC_EXPORT_YEAR                 258
#define IDC_FONT                        259
#define IDC_FONT2                       260
#define IDC_FONT_BUTTON                 261
#define IDC_FONT_COLHDR                 262
#define IDC_FONT_CURPLY                 263
#define IDC_FONT_PANEL                  264
#define IDC_FONTSIZE                    265
#define IDC_FONTSIZE2                   266
#define IDC_FONTSIZE_COLHDR             267
#define IDC_FONTSIZE_CURPLY             268
#define IDC_FONTSIZE_PANEL              269
#define IDC_GAAS                        270
#define IDC_GENRES                      271
#define IDC_GENRESLABEL                 272
#define IDC_GETTEXTFIELD                273
#define IDC_GETTEXTFIELD_DESC           274
#define IDC_GO                          275
#define IDC_HIDE_GENRE                  276
#define IDC_HYPERLINK                   277
#define IDC_ID3_DISPLAY                 278
#define IDC_ID3_SEARCHFOR_LABEL         279
#define IDC_ID3MODIFY_LABEL             280
#define IDC_ID3MODIFY_PROGRESS          281
#define IDC_ID3MODIFY_STATUS            282
#define IDC_IMPL_VERSION_LABEL          283
#define IDC_INFO_BUTTON                 284
#define IDC_INIT_ABORT                  285
#define IDC_INIT_LABEL                  286
#define IDC_INIT_LABEL2                 287
#define IDC_INIT_PROGRESS               288
#define IDC_INIT_STATUS                 289
#define IDC_INPUT_LIST                  290
#define IDC_IR_B_00_UP                  291
#define IDC_IR_B_01_DOWN                292
#define IDC_IR_B_02_LEFT                293
#define IDC_IR_B_03_RIGHT               294
#define IDC_IR_B_04_SELECT              295
#define IDC_IR_B_05_MENU                296
#define IDC_IR_B_06_EXIT                297
#define IDC_IR_B_07_DELETE              298
#define IDC_IR_B_08_VOLUP               299
#define IDC_IR_B_09_VOLDOWN             300
#define IDC_IR_B_10_PAGEUP              301
#define IDC_IR_B_11_PAGEDOWN            302
#define IDC_IR_B_12_PLAY                303
#define IDC_IR_B_13_PAUSE               304
#define IDC_IR_B_14_STOP                305
#define IDC_IR_B_15_NEXT                306
#define IDC_IR_B_16_PREVIOUS            307
#define IDC_IR_B_17_FASTFORWARD         308
#define IDC_IR_B_18_REVERSE             309
#define IDC_IR_B_19_ALPHAUP             310
#define IDC_IR_B_20_ALPHADOWN           311
#define IDC_IR_B_21_RANDOM              312
#define IDC_IR_B_22_SHUFFLE             313
#define IDC_IR_B_23_CLEAR               314
#define IDC_IR_B_24_LOAD                315
#define IDC_IR_B_25_SAVE                316
#define IDC_IR_D_00_UP_DESC             317
#define IDC_IR_D_01_DOWN_DESC           318
#define IDC_IR_D_02_LEFT_DESC           319
#define IDC_IR_D_03_RIGHT_DESC          320
#define IDC_IR_D_04_SELECT_DESC         321
#define IDC_IR_D_05_MENU_DESC           322
#define IDC_IR_D_06_EXIT_DESC           323
#define IDC_IR_D_07_DELETE_DESC         324
#define IDC_IR_D_08_VOLUP_DESC          325
#define IDC_IR_D_09_VOLDOWN_DESC        326
#define IDC_IR_D_10_PAGEUP_DESC         327
#define IDC_IR_D_11_PAGEDOWN_DESC       328
#define IDC_IR_D_12_PLAY_DESC           329
#define IDC_IR_D_13_PAUSE_DESC          330
#define IDC_IR_D_14_STOP_DESC           331
#define IDC_IR_D_15_NEXT_DESC           332
#define IDC_IR_D_16_PREVIOUS_DESC       333
#define IDC_IR_D_17_FASTFORWARD_DESC    334
#define IDC_IR_D_18_REVERSE_DESC        335
#define IDC_IR_D_19_ALPHAUP_DESC        336
#define IDC_IR_D_20_ALPHADOWN_DESC      337
#define IDC_IR_D_21_RANDOM_DESC         338
#define IDC_IR_D_22_SHUFFLE_DESC        339
#define IDC_IR_D_23_CLEAR_DESC          340
#define IDC_IR_D_24_LOAD_DESC           341
#define IDC_IR_D_25_SAVE_DESC           342
#define IDC_IR_READ_TEST_LABEL          343
#define IDC_IR_S_00_UP_STATUS           344
#define IDC_IR_S_01_DOWN_STATUS         345
#define IDC_IR_S_02_LEFT_STATUS         346
#define IDC_IR_S_03_RIGHT_STATUS        347
#define IDC_IR_S_04_SELECT_STATUS       348
#define IDC_IR_S_05_MENU_STATUS         349
#define IDC_IR_S_06_EXIT_STATUS         350
#define IDC_IR_S_07_DELETE_STATUS       351
#define IDC_IR_S_08_VOLUP_STATUS        352
#define IDC_IR_S_09_VOLDOWN_STATUS      353
#define IDC_IR_S_10_PAGEUP_STATUS       354
#define IDC_IR_S_11_PAGEDOWN_STATUS     355
#define IDC_IR_S_12_PLAY_STATUS         356
#define IDC_IR_S_13_PAUSE_STATUS        357
#define IDC_IR_S_14_STOP_STATUS         358
#define IDC_IR_S_15_NEXT_STATUS         359
#define IDC_IR_S_16_PREVIOUS_STATUS     360
#define IDC_IR_S_17_FASTFORWARD_STATUS  361
#define IDC_IR_S_18_REVERSE_STATUS      362
#define IDC_IR_S_19_ALPHAUP_STATUS      363
#define IDC_IR_S_20_ALPHADOWN_STATUS    364
#define IDC_IR_S_21_RANDOM_STATUS       365
#define IDC_IR_S_22_SHUFFLE_STATUS      366
#define IDC_IR_S_23_CLEAR_STATUS        367
#define IDC_IR_S_24_LOAD_STATUS         368
#define IDC_IR_S_25_SAVE_STATUS         369
#define IDC_IRCOM0NONE                  370
#define IDC_IRCOM1                      371
#define IDC_IRCOM2                      372
#define IDC_IRCOM3                      373
#define IDC_IRCOM4                      374
#define IDC_IRCOM5                      375
#define IDC_IRCOM6                      376
#define IDC_IRCOM7                      377
#define IDC_IRCOM8                      378
#define IDC_IRCOMPORT_STATUS            379
#define IDC_IRCONFIG_BUTTON             380
#define IDC_IRDELAY                     381
#define IDC_IRHELPBUTTON                382
#define IDC_IRINITIALIZE                383
#define IDC_IRMAN_SETUP                 384
#define IDC_IRRECORD                    385
#define IDC_IRTEST                      386
#define IDC_IRTEST_STATUS               387
#define IDC_IRTYPE                      388
#define IDC_LIBRARY_VERSION_LABEL       389
#define IDC_LIST1                       390
#define IDC_LIST2                       391
#define IDC_LIST3                       392
#define IDC_LIST4                       393
#define IDC_LIST6                       394
#define IDC_LOCATION_BUTTON             395
#define IDC_LPD_NAMES_LABEL             396
#define IDC_LPD_SONGS_LABEL             397
#define IDC_LPD_TITLE                   398
#define IDC_MAKEDEFAULT                 399
#define IDC_MASTER_SLIDER               400
#define IDC_MDB_LOCATION                401
#define IDC_MENU_BUTTON                 402
#define IDC_MESSAGE_BOX                 403
#define IDC_MESSAGE_BOX2                404
#define IDC_MESSAGEBOX_CANCEL           405
#define IDC_MESSAGEBOX_OK               406
#define IDC_MOREID3                     407
#define IDC_MP3_ADD                     408
#define IDC_MP3_ADD_EXT                 409
#define IDC_MP3_EXTENSION               410
#define IDC_MP3_REMOVE                  411
#define IDC_MSG                         412
#define IDC_MUSIC_BUTTON                413
#define IDC_NAME_LABEL                  414
#define IDC_NETWORK_PROGRESS1           415
#define IDC_NETWORK_PROGRESS2           416
#define IDC_NETWORK_STATUS_LABEL        417
#define IDC_OLDALBUM                    418
#define IDC_OLDARTIST                   419
#define IDC_OLDGENRE                    420
#define IDC_OLDTITLE                    421
#define IDC_OLDTRACK                    422
#define IDC_OLDYEAR                     423
#define IDC_OPEN_FILE_BUTTON            424
#define IDC_OPEN_URL_BUTTON             425
#define IDC_OPTIONS_BUTTON              426
#define IDC_OUTPUT_LIST                 427
#define IDC_PASSWORD_MSG                428
#define IDC_PCM_SLIDER                  429
#define IDC_PICTURE                     430
#define IDC_PICTURE_CTRL                431
#define IDC_PICTURES_BUTTON             432
#define IDC_PLAY_BUTTON                 433
#define IDC_PLAYER_STATUS               434
#define IDC_PLAYING_LABEL               435
#define IDC_PLAYLIST                    436
#define IDC_PLAYLIST_CANCEL             437
#define IDC_PLAYLIST_CLOSE              438
#define IDC_PLAYLIST_DELETE             439
#define IDC_PLAYLIST_DOWN               440
#define IDC_PLAYLIST_HEIGHT             441
#define IDC_PLAYLIST_LOAD               442
#define IDC_PLAYLIST_NAMES              443
#define IDC_PLAYLIST_RENAME             444
#define IDC_PLAYLIST_SAVE               445
#define IDC_PLAYLIST_SONGS              446
#define IDC_PLAYLIST_UP                 447
#define IDC_PLAYLISTLABEL               448
#define IDC_PMENUCLEARPLAYLIST          449
#define IDC_PMENUEXIT                   450
#define IDC_PMENUHELP                   451
#define IDC_PMENULOADPLAYLIST           452
#define IDC_PMENUPAUSE                  453
#define IDC_PMENUPLAY                   454
#define IDC_PMENURANDOMIZEPLAYLIST      455
#define IDC_PMENUSAVEPLAYLIST           456
#define IDC_PMENUSHUFFLEPLAYLIST        457
#define IDC_PMENUSTOP                   458
#define IDC_POSITION_LABEL              459
#define IDC_POSITION_SLIDER             460
#define IDC_PRODVERSION                 461
#define IDC_PROGRESS_ABORT              462
#define IDC_PROGRESS_LABEL              463
#define IDC_PROGRESS_LABEL2             464
#define IDC_PROGRESS_PROGRESS           465
#define IDC_PROGRESS_STATUS             466
#define IDC_PURCHASE_BUTTON             467
#define IDC_REFRESH_DRIVES              468
#define IDC_REPLAYGAIN                  469
#define IDC_REPLAYGAIN_MULTIPLIER       470
#define IDC_RESTORE_SKIN_DEFAULTS       471
#define IDC_ROUND_CORNERS               472
#define IDC_RUNATSTARTUP                473
#define IDC_SAMPLE                      474
#define IDC_SAMPLE2                     475
#define IDC_SAMPLE_COLHDR               476
#define IDC_SAMPLE_CURPLY               477
#define IDC_SAMPLE_GROUP                478
#define IDC_SAMPLE_HIGH                 479
#define IDC_SAMPLE_PANEL                480
#define IDC_SAMPLE_PLAYLIST             481
#define IDC_SAMPLE_SEL                  482
#define IDC_SAMPLE_TITLES               483
#define IDC_SAVEPLAYLIST_BOX            484
#define IDC_SCAN_RESULTS                485
#define IDC_SCROLLBAR1                  486
#define IDC_SEARCH_CANCEL               487
#define IDC_SEARCH_CLEAR                488
#define IDC_SEARCH_GO                   489
#define IDC_SEARCH_STATUS               490
#define IDC_SEARCH_TEXT                 491
#define IDC_SENDINFO                    492
#define IDC_SET_DEFAULT                 493
#define IDC_SKIN_DELETE                 494
#define IDC_SKIN_LIST                   495
#define IDC_SLIDER                      496
#define IDC_SLIDER1                     497
#define IDC_SLIDER2                     498
#define IDC_SLIDER3                     499
#define IDC_SLIDER4                     500
#define IDC_SLIDER5                     501
#define IDC_SLIDER6                     502
#define IDC_SLIDER7                     503
#define IDC_SLIDER8                     504
#define IDC_SONGS                       505
#define IDC_SONGSLABEL                  506
#define IDC_SPIN_GENRE                  507
#define IDC_SPIN_PLAYLIST               508
#define IDC_STATE_LABEL                 509
#define IDC_STATIC1                     510
#define IDC_STOP_BUTTON                 511
#define IDC_STREAM_PROPERTIES           512
#define IDC_SWAP_SETTINGS_BUTTON        513
#define IDC_SWAP_SETTINGS_LABEL         514
#define IDC_SYNC_VERSION_LABEL          515
#define IDC_TAG_FILE                    516
#define IDC_TAGDATA                     517
#define IDC_TAGFILE                     518
#define IDC_TIMECODE_LABEL              519
#define IDC_TREE                        520
#define IDC_TYPE_LABEL                  521
#define IDC_URL_EDIT                    522
#define IDC_VALIDATE_PW                 523
#define IDC_VIDEO_BUTTON                524
#define IDC_VOLUME_BUTTON               525
#define IDC_VOLUME_LABEL                526
#define IDC_VOLUME_SLIDER               527
#define IDC_WMP                         528
#define IDC_XAUDIO_STATUS               529
#define ID__CLEAR                       32771
#define ID__CONFIG                      32772
#define ID__EXIT                        32773
#define ID__LOADPLAYLIST                32774
#define ID__PLAYER_CLEAR                32775
#define ID__PLAYER_FASTFORWARD          32776
#define ID__PLAYER_LOAD                 32777
#define ID__PLAYER_NEXTSONG             32778
#define ID__PLAYER_PAUSE                32779
#define ID__PLAYER_PLAY                 32780
#define ID__PLAYER_PREVIOUSSONG         32781
#define ID__PLAYER_RANDOMIZE            32782
#define ID__PLAYER_REVERSESKIP          32783
#define ID__PLAYER_SAVE                 32784
#define ID__PLAYER_SHUFFLE              32785
#define ID__PLAYER_STOP                 32786
#define ID__PLAYER_VOLUMEDOWN           32787
#define ID__PLAYER_VOLUMEUP             32788
#define ID__SAVEPLAYLIST                32789
#define ID__SHUFFLE                     32790
#define ID_ADDTO_PLAYLIST               32791
#define ID_ALPHA_DOWN                   32792
#define ID_ALPHA_UP                     32793
#define ID_DELETE_FROM_LIBRARY          32794
#define ID_DELETE_FROM_PL               32795
#define ID_EDIT_ID3TAG                  32796
#define ID_EXPORT_OUPUT_BROWSE          32797
#define ID_EXPORT_TAGS                  32798
#define ID_EXPORT_TEMPLATE_BROWSE       32799
#define ID_MENU                         32800
#define ID_MENU_ADD                     32801
#define ID_MENU_CLEARPLAYLIST           32802
#define ID_MENU_EDITPL                  32803
#define ID_MENU_EXIT                    32804
#define ID_MENU_EXPORT                  32805
#define ID_MENU_HELP                    32806
#define ID_MENU_LOADPLAYLIST            32807
#define ID_MENU_OPTIONS                 32808
#define ID_MENU_PAUSE                   32809
#define ID_MENU_PLAY                    32810
#define ID_MENU_RANDOMIZE_PLAYLIST      32811
#define ID_MENU_SAVEPLAYLIST            32812
#define ID_MENU_SCAN                    32813
#define ID_MENU_SCANNEW                 32814
#define ID_MENU_SHUFFLEPLAYLIST         32815
#define ID_MENU_STOP                    32816
#define ID_MENUITEM32803                32817
#define ID_MYTEST                       32818
#define ID_OPEN_FILE_BUTTON             32819
#define ID_PMENU_CLEAR                  32820
#define ID_PMENU_EXIT                   32821
#define ID_PMENU_HELP                   32822
#define ID_PMENU_LOADPLAYLIST           32823
#define ID_PMENU_PAUSE                  32824
#define ID_PMENU_PLAY                   32825
#define ID_PMENU_SHUFFLE                32826
#define ID_PMENU_STOP                   32827
#define ID_QUICK_PLAY                   32828
#define ID_SEARCH                       32829
#define ID_XXX                          32830

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        96
#define _APS_NEXT_COMMAND_VALUE         32831
#define _APS_NEXT_CONTROL_VALUE         530
#define _APS_NEXT_SYMED_VALUE           630
#endif
#endif
